# Generated by Django 6.0.6 on 2026-06-15 01:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('agreement_type', models.CharField(choices=[('NDA', 'NDA'), ('MSA', 'MSA'), ('TEAMING', 'Teaming Agreement'), ('SUBCONTRACTOR', 'Subcontractor Agreement'), ('LICENSING', 'Licensing Agreement'), ('LOI', 'Letter Of Intent'), ('WORK_ORDER', 'Work Order')], max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Awaiting Signature'), ('SIGNED', 'Signed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('initiator_name', models.CharField(max_length=255)),
                ('initiator_title', models.CharField(max_length=255)),
                ('counterparty_company', models.CharField(max_length=255)),
                ('counterparty_contact_name', models.CharField(max_length=255)),
                ('counterparty_contact_title', models.CharField(max_length=255)),
                ('counterparty_email', models.EmailField(max_length=254)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
