# Generated by Django 6.0.6 on 2026-06-20 22:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=5)),
                ('background', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_title', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('initiator_name', models.CharField(max_length=100)),
                ('initiator_title', models.CharField(max_length=100)),
                ('agreement_type', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('intellectual_property', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('governing_law', models.CharField(max_length=100)),
                ('link_expiration_days', models.IntegerField(default=7)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Awaiting Signature'), ('SIGNED', 'Signed')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agreements.partner')),
            ],
        ),
    ]
