# Generated by Django 6.0.6 on 2026-06-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='initiator_company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='agreement',
            name='initiator_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='agreement',
            name='initiator_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='agreement',
            name='initiator_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
