# Generated by Django 6.0.6 on 2026-06-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_agreement_initiator_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='section_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='section_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='section_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='section_4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='section_5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='section_6',
            field=models.TextField(blank=True),
        ),
    ]
