# Generated by Django 6.0.6 on 2026-06-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0004_agreement_initiator_signed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='agreement',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
