# Generated by Django 6.0.6 on 2026-06-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0005_agreement_otp_code_agreement_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='counterparty_signature',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='agreement',
            name='counterparty_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
