# Generated by Django 6.0.6 on 2026-06-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0006_agreement_counterparty_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='pdf_url',
            field=models.URLField(blank=True),
        ),
    ]
